language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.7.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.3.*'
    - php: 7.0
      env: TARGET=cs_dry_run
    - php: 5.6
      env: DEPENDENCIES="symfony/lts:^2"
    - php: 7.1
      env: DEPENDENCIES="symfony/lts:^3"
    - php: 7.1
      env: DEPENDENCIES='dev' SYMFONY_VERSION='4.0.*'
  allow_failures:
    - php: hhvm

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}"; fi;
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: phpunit
