language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TARGET=cs_dry_run
    - php: 5.6
      env: DEPENDENCIES="symfony/lts:^2"
    - php: 7.1
      env: DEPENDENCIES="symfony/lts:^3"
  allow_failures:
    - php: hhvm

before_install:
  - if [[ -v $DEPENDENCIES ]]; then composer require --no-update $DEPENDENCIES; fi;
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: phpunit
